### ISSUE TITLE
BinarySearchTree 

### ISSUE THREAD

**Issue by rusdevops** [lisa-bella97/BinarySearchTree#1]
@lisa-bella97 
- отсутствует `CMakeLists.txt` файл
- стоит придерживаться одного стиля (`std::endl` vs `"\n"`) [здесь](https://github.com/lisa-bella97/BinarySearchTree/blob/ec1e6f3194ee2c6e8e33aaa4479ac58c37e04603/Main.cpp#L34)

**Comment by lisa-bella97** [comment]
Сделано

**Comment by rusdevops** [comment]
closed this in [0091cb0](https://github.com/lisa-bella97/BinarySearchTree/commit/0091cb019a5508a258ae6d276d4868744ba8b2df) and [5ee6273](https://github.com/lisa-bella97/BinarySearchTree/commit/5ee6273d6678b0ff5962d3f1a7dedea00b46a24e)
