### ISSUE TITLE
Second overview

### ISSUE THREAD

**Issue by rusdevops** [lisa-bella97/BinarySearchTree#2]
- [x] Отсутствует проверка результата вызова оператора ввода. [здесь](https://github.com/lisa-bella97/BinarySearchTree/blob/5ee6273d6678b0ff5962d3f1a7dedea00b46a24e/BinarySearchTree.h#L34), [здесь](https://github.com/lisa-bella97/BinarySearchTree/blob/5ee6273d6678b0ff5962d3f1a7dedea00b46a24e/BinarySearchTree.h#L40), [здесь](https://github.com/lisa-bella97/BinarySearchTree/blob/5ee6273d6678b0ff5962d3f1a7dedea00b46a24e/BinarySearchTree.h#L50) и [здесь](https://github.com/lisa-bella97/BinarySearchTree/blob/5ee6273d6678b0ff5962d3f1a7dedea00b46a24e/BinarySearchTree.h#L55).
- [x] Дублирование кода. [](https://github.com/lisa-bella97/BinarySearchTree/blob/5ee6273d6678b0ff5962d3f1a7dedea00b46a24e/BinarySearchTree.h#L90-L91) и [здесь](https://github.com/lisa-bella97/BinarySearchTree/blob/5ee6273d6678b0ff5962d3f1a7dedea00b46a24e/BinarySearchTree.h#L97-L98). Стоит в конструкторе с параметром в списке инициализации вызвать конструтор по умолчанию.
- [x] Некорректная реализация метода `insert`. [здесь](https://github.com/lisa-bella97/BinarySearchTree/blob/5ee6273d6678b0ff5962d3f1a7dedea00b46a24e/BinarySearchTree.h#L123). Данная реализация увеличивает алгоритмическую сложность метода вставки в 2 раза.
- [ ] Репозиторий не соответствует заданной структуре.

**Comment by lisa-bella97** [comment]
closed this in 4930e0c
