### ISSUE TITLE
II stage

### ISSUE THREAD

**Issue by rusdevops** [lisa-bella97/BinarySearchTree#3]
- [x] Перенести логику работы метода `BinarySearchTree::copyTree` на метод `Node::copy`
- [x] В реализации оператора `auto operator >> (std::istream& in, BinarySearchTree<T>& tree) -> std::istream&` допущено не определенное поведение.
- [x] Оператор `operator << (std::ostream&, const BinarySearchTree<T>&)` реализован не в соответствии с заданием.
- [x] Метод `auto BinarySearchTree<T>::equal(Node *firstNode, Node *secondNode) const -> bool` имеет большой уровень вложенности.

**Comment by lisa-bella97** [comment]
Исправила 1, 3 и 4 замечания в 8914807.
Насчет 2 замечания, непонятно, где возникает неопределенное поведение

**Comment by lisa-bella97** [comment]
Closed this in 8fa35c6
