### ISSUE TITLE
III stage

### ISSUE THREAD

**Issue by rusdevops** [lisa-bella97/BinarySearchTree#4]
- [x] Измените форму синтаксиса директивы `include`. [здесь](https://github.com/lisa-bella97/BinarySearchTree/blob/04f0cb548e1aae558129dc6b0f1e8302916cdea8/examples/main.cpp#L1),
  [здесь](https://github.com/lisa-bella97/BinarySearchTree/blob/04f0cb548e1aae558129dc6b0f1e8302916cdea8/tests/size.cpp#L1),
  [здесь](https://github.com/lisa-bella97/BinarySearchTree/blob/04f0cb548e1aae558129dc6b0f1e8302916cdea8/tests/insert.cpp#L1) и
  [здесь](https://github.com/lisa-bella97/BinarySearchTree/blob/04f0cb548e1aae558129dc6b0f1e8302916cdea8/tests/find.cpp#L1)

**Comment by lisa-bella97** [comment]
closed this in 0f7e5d6
